language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  
before_script:
  - composer install --no-interaction
  
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml
